kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: voip-manager
  namespace: voip
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods","endpoints","services","nodes"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["*"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manager
  namespace: voip
subjects:
  - kind: User
    name: system:serviceaccount:voip:default
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: voip-manager
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prom-admin
  namespace: voip
rules:
  - apiGroups: [""]
    resources: ["pods","endpoints","services","nodes"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prom-rbac
  namespace: voip
subjects:
  - kind: ServiceAccount
    name: default
    namespace: voip
roleRef:
  kind: ClusterRole
  name: prom-admin
  apiGroup: rbac.authorization.k8s.io

